### PR TITLE
Ported to version 6.1.1 of automapper and 10.0.3 of newtonsoft.json

### PR DESCRIPTION
**Pull request by rollsch**
Ported to version 6.1.1 of automapper and 10.0.3 of newtonsoft.json

### CODE REVIEW

**Comment by fhls** [comment]
This PR changes the Automapper static API to instance API, looks proper and solve my problem!

**Comment by rollsch** [comment]
eway are not interested in maintaining it. I made a paid support request to them about a month ago and they keep stalling saying its too many lines of code to review.

I guess we are only paying them 2.2% of our total revenue and did all of their work for free.... I guess it is a pretty tall ask to update this.

: /

**Comment by incarnate** [comment]
My apologies for the long delay in getting this change tested and released. I've just pushed version 1.6.0 of the eWAY .NET SDK to NuGet with this change in it - in fact we've gone all the way up to AutoMapper 6.2.0.

Thanks @rolandh for submitting the fix, I will try and get through any future PRs faster.

**Comment by rollsch** [comment]
incarnate can you create a NetCore version of this nuget package? We will be moving to NetCore soon.

**Pull request merged**
